#!/bin/bash

function print_error {
    echo "`basename $0`: $1"
    exit 1
}

function print_usage {
    echo "Usage: `basename $0` [options] kernel-version tgz-file"
    echo "Options"
    echo "  -h            Show this information"
    echo "  -l            Include /etc/lilo.conf"
}

LILO_CONF=""

while (( $# > 2 ))
do
    case $1 in
	"-l")
	    LILO_CONF="/etc/lilo.conf"
	    shift
	    ;;
	*)
	    print_error "incorrect option $1"
	    ;;
    esac
done

if (( $# != 2 )); then
    print_usage;
    exit 0
fi

set -e

KVER=$1
TGZFILE=$2
echo "Packaging emoving $KVER ..."

tar zcvf $TGZFILE \
    $(readlink /lib/modules/$KVER/source) \
    /lib/modules/$KVER \
    /boot/vmlinuz-$KVER \
    /boot/initrd-$KVER.gz \
    /boot/System.map-$KVER \
    /boot/config-$KVER $LILO_CONF
    
echo "Be sure to update /etc/lilo.conf"
