#!/bin/bash

function print_error {
    echo "`basename $0`: $1"
    exit 1
}

function print_usage {
    echo "Usage: `basename $0` version"
}

function remove {
    if [ ! -e $1 ]; then
	print_error "$1 not found"
    fi
    rm -rvf $1
}

if (( $# != 1 )); then
    print_usage;
    exit 0
fi

set -e

KVER=$1
echo "Removing $KVER ..."

remove /lib/modules/$KVER
remove /boot/vmlinuz-$KVER
remove /boot/initrd-$KVER.gz
remove /boot/System.map-$KVER
remove /boot/config-$KVER

echo "Be sure to update /etc/lilo.conf"
